# Generated by Django 4.0 on 2021-12-26 17:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.UUID("11119015-f90e-4881-89d8-d26c2e2489ca"), primary_key=True, serialize=False
                    ),
                ),
                ("user_name", models.CharField(max_length=64)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("birthday_year", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
