# Generated by Django 4.0 on 2021-12-26 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.AddField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7af010a6-4a2d-4fe6-bed2-f7afd569abce'), primary_key=True, serialize=False),
        ),
    ]
