# Generated by Django 4.0 on 2021-12-26 17:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_remove_author_id_author_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("cc0ae9ac-af04-4289-8880-1a36c9973894"), primary_key=True, serialize=False
            ),
        ),
    ]
